// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from "react";

import { a } from "@react-spring/three";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

const Lobby: React.FC = (props: any) => {
  const { nodes, materials } = useGLTF("./assets/lobby.glb");
  const avatarRef = useRef();

  return (
    <a.group ref={avatarRef} {...props} dispose={null} scale={[2.2, 1, 1]}>
      <mesh
        geometry={nodes.mesh_279.geometry}
        material={materials.mat_244}
        position={[5, -15, -20]}
        rotation={[-1.7, 0, 9.4]}
        scale={-0.1}
      >
        <mesh
          name="mesh_252"
          castShadow
          receiveShadow
          geometry={nodes.mesh_252.geometry}
          material={materials.mat_217}
        />
        <mesh
          name="mesh_278"
          castShadow
          receiveShadow
          geometry={nodes.mesh_278.geometry}
          material={materials.mat_243}
        />
        <mesh
          name="mesh_280"
          castShadow
          receiveShadow
          geometry={nodes.mesh_280.geometry}
          material={materials.mat_245}
        />
        <mesh
          name="mesh_281"
          castShadow
          receiveShadow
          geometry={nodes.mesh_281.geometry}
          material={materials.mat_246}
        />
        <mesh
          name="mesh_283"
          castShadow
          receiveShadow
          geometry={nodes.mesh_283.geometry}
          material={materials.mat_248}
        />
        <mesh
          name="mesh_284"
          castShadow
          receiveShadow
          geometry={nodes.mesh_284.geometry}
          material={materials.mat_249}
        />
        <mesh
          name="mesh_285"
          castShadow
          receiveShadow
          geometry={nodes.mesh_285.geometry}
          material={materials.mat_250}
        />
        <mesh
          name="mesh_286"
          castShadow
          receiveShadow
          geometry={nodes.mesh_286.geometry}
          material={materials.mat_251}
        />
        <mesh
          name="mesh_287"
          castShadow
          receiveShadow
          geometry={nodes.mesh_287.geometry}
          material={materials.mat_252}
        />
        <mesh
          name="mesh_288"
          castShadow
          receiveShadow
          geometry={nodes.mesh_288.geometry}
          material={materials.mat_253}
        />
        <mesh
          name="mesh_289"
          castShadow
          receiveShadow
          geometry={nodes.mesh_289.geometry}
          material={materials.mat_254}
        />
        <mesh
          name="mesh_290"
          castShadow
          receiveShadow
          geometry={nodes.mesh_290.geometry}
          material={materials.mat_255}
        />
        <mesh
          name="mesh_291"
          castShadow
          receiveShadow
          geometry={nodes.mesh_291.geometry}
          material={materials.mat_256}
        />
        <mesh
          name="mesh_292"
          castShadow
          receiveShadow
          geometry={nodes.mesh_292.geometry}
          material={materials.mat_257}
        />
        <mesh
          name="mesh_293"
          castShadow
          receiveShadow
          geometry={nodes.mesh_293.geometry}
          material={materials.mat_258}
        />
        <mesh
          name="mesh_294"
          castShadow
          receiveShadow
          geometry={nodes.mesh_294.geometry}
          material={materials.mat_259}
        />
        <mesh
          name="mesh_295"
          castShadow
          receiveShadow
          geometry={nodes.mesh_295.geometry}
          material={materials.mat_260}
        />
        <mesh
          name="mesh_296"
          castShadow
          receiveShadow
          geometry={nodes.mesh_296.geometry}
          material={materials.mat_261}
        />
      </mesh>
    </a.group>
  );
};

// const Lobby: React.FC<SkyProps> = () => {
//   const lobbyScene = useGLTF("./assets/lobby.glb");

//   return (
//     <mesh position={[0, 100, 0]}>
//       <primitive object={lobbyScene.scene} />
//     </mesh>
//   );
// };

export default Lobby;
